dts <- cbind(male=mdeaths,female=fdeaths,time=1:length(mdeaths))
ddf <- melt(as.data.frame(dts),id="time")
names(ddf) <- c("time","sex","deaths")
library(ggplot2)
qplot(time,deaths,data=ddf,colour=sex,geom="line")+xlim(-5,77)
